---
- name: Checking for the correct deploy mode...
  ansible.builtin.fail:
    msg: |
      Virtual Machine {{ custom_vm_name | default(vm_name) }} doesn't exist, use the deploy command first!
  when:
    - fresh_deploy
    - role_only or role_only_wp or single_role is defined

- name: Configuring {{ custom_vm_name | default(vm_name) }} in Linode...
  linode.cloud.instance:
    api_token: "{{ linode_api_token }}"
    label: "{{ custom_vm_name | default(vm_name) }}"
    type: "{{ linode_vm_type | default('g6-dedicated-2') }}"
    region: "{{ linode_vm_region | default('eu-central') }}"
    image: "{{ linode_image }}"
    root_pass: "{{ template_password if fresh_deploy else omit }}"
    tags:
      - "{{ project_fullname | default('untagged') }}"
    state: present
  register: linode_vm
  delegate_to: localhost
  become: false

- name: Setting IP address facts for {{ inventory_hostname }}...
  ansible.builtin.set_fact:
    connection_address: "{{ linode_vm.instance.ipv4[0] | ansible.utils.ipaddr('address') }}"
    connection_nic_ipv4: "{{ linode_vm.instance.ipv4[0] | ansible.utils.ipaddr('address') }}"
    connection_nic_ipv6: "{{ linode_vm.instance.ipv6 | ansible.utils.ipaddr('address') }}"
    egress_nic_ipv4: "{{ linode_vm.instance.ipv4[0] | ansible.utils.ipaddr('address') }}"
    egress_nic_ipv6: "{{ linode_vm.instance.ipv6 | ansible.utils.ipaddr('address') }}"

    # Deprecated, to be removed in future releases
    primary_ipv4: "{{ linode_vm.instance.ipv4[0] | ansible.utils.ipaddr('address') }}"
    primary_ipv6: "{{ linode_vm.instance.ipv6 | ansible.utils.ipaddr('address') }}"
