---
# All of the vmware.vmware_rest have retries for stability
- name: Checking if {{ custom_vm_name | default(vm_name) }} already exists...
  vmware.vmware_rest.vcenter_vm_info:
    filter_names: "{{ custom_vm_name | default(vm_name) }}"
  register: vcenter_vm_info
  until: not vcenter_vm_info.failed
  retries: 5
  delay: 2
  delegate_to: localhost
  become: false

- name: Including {{ custom_vm_name | default(vm_name) }} removal tasks...
  ansible.builtin.include_tasks: remove.yml
  when: deploy_mode in ['undeploy', 'redeploy']

- name: Including {{ custom_vm_name | default(vm_name) }} creation tasks...
  ansible.builtin.include_tasks: create.yml
