---
- name: Missing required variables...
  ansible.builtin.fail:
    msg: |
      Following variables are required to run this role:
      - vcenter_hostname
      - vcenter_username or project_deployer_username or deployer_username
      - vcenter_password or project_deployer_password or deployer_password
  when: vmware_defaults.hostname is ansible.builtin.falsy
    or vmware_defaults.username is ansible.builtin.falsy
    or vmware_defaults.password is ansible.builtin.falsy

- name: Looking up the {{ custom_vm_name | default(vm_name) }} VM...
  vmware.vmware.guest_info:
    guest_name: "{{ custom_vm_name | default(vm_name) }}"
  register: vcenter_vm_info
  delegate_to: localhost
  become: false

- name: Including {{ custom_vm_name | default(vm_name) }} removal tasks...
  ansible.builtin.include_tasks: remove.yml
  when: deploy_mode in ['undeploy', 'redeploy']

- name: Including {{ custom_vm_name | default(vm_name) }} creation tasks...
  ansible.builtin.include_tasks: create.yml

- name: Including {{ custom_vm_name | default(vm_name) }} reconfiguration tasks...
  ansible.builtin.include_tasks: reconfigure.yml
  when:
    - not role_only_wp # Not reconfiguring when running from pre_vm_role
    - not role_only # Not reconfiguring on role only
    - not fresh_deploy or machine_operations_vsphere_content_library_name != {} # Configuring when not fresh_deploy or content library is used
    - machine_operations_reconfigure_vm_on_deploy
    - vcenter_vm_info.guests != [] # Only reconfigure if VM exists
