---
- name: Configuring VM network on Proxmox...
  become: false
  delegate_to: localhost
  block:
    # Retrying until the host is available, might take some time depending on the OS.
    - name: Getting {{ custom_vm_name | default(vm_name) }} network configuration...
      community.proxmox.proxmox_vm_info:
        name: "{{ custom_vm_name | default(vm_name) }}"
        config: current
        network: true
      register: proxmox_vm_info
      until: not proxmox_vm_info.failed
      retries: 60
      delay: 5

    - name: Creating a list of MAC addresses...
      ansible.builtin.set_fact:
        # Skipping the first MAC address as it is the loopback interface.
        configure_networking_mac_addresses: "{{ (proxmox_vm_info.proxmox_vms[0].network | map(attribute='hardware-address') | list)[1:] }}"

    - name: Including {{ customization_method }} network configuration tasks...
      ansible.builtin.include_tasks: "{{ customization_method }}.yml"
