---
- name: Looking up the {{ custom_vm_name | default(vm_name) }} VM...
  vmware.vmware.guest_info:
    guest_name: "{{ custom_vm_name | default(vm_name) }}"
  register: vcenter_vm_info

- name: Renaming VM in vSphere environment...
  when: vcenter_vm_info.guests != []
  block:
    - name: Looking up the existing VM UUID...
      community.vmware.vmware_guest_info:
        datacenter: "{{ datacenter }}"
        name: "{{ old_vm_name | default(custom_vm_name) | default(vm_name) }}"
      register: old_vcenter_vm_info
      delegate_to: localhost

    - name: Renaming {{ old_vm_name | default(custom_vm_name) | default(vm_name) }} VM to {{ new_vm_name }}...
      community.vmware.vmware_guest:
        datacenter: "{{ datacenter }}"
        uuid: "{{ old_vcenter_vm_info.instance.hw_product_uuid }}"
        name: "{{ new_vm_name }}"
      delegate_to: localhost
