---
- name: Printing deprecation message...
  block:
    - name: DEPRECATED DATA STRUCTURE
      ansible.builtin.debug:
        msg: |
          vault_mitm_ca_pki_engine_name variable found
          Intermediate CA(s) configuration must be defined as a list not as a single variable.
          Check the nova.core.vault role defaults for an example on how to define the MitM CA(s) as a list.
          No MitM CA configuration will be done.

    - name: Sleeping to read...
      ansible.builtin.wait_for:
        timeout: 30
      become: false
      delegate_to: localhost
