---
services:
  nexus:
    image: sonatype/nexus3:{{ nexus_version }}
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    volumes:
      - nexus_data:/nexus-data
    environment:
      NEXUS_SECRETS_KEY_FILE: /nexus-data/nexus.secrets.json
    logging:
      driver: json-file
      options:
        max-size: 250m
        max-file: "1"

volumes:
  nexus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ nexus_container_config_folder }}/data"

networks:
  default:
    name: "{{ nexus_docker_network }}"
    external: true
