---
- name: Delegating poweron tasks to localhost...
  delegate_to: localhost
  become: false
  block:
    - name: Powering on {{ custom_vm_name | default(vm_name) }}...
      vmware.vmware.vm_powerstate:
        name: "{{ custom_vm_name | default(vm_name) }}"
        datacenter: "{{ datacenter }}"
        state: powered-on
        force: true # Required to power on a VM that is in a suspended state

    - name: Waiting for {{ custom_vm_name | default(vm_name) }} to power on...
      vmware.vmware.guest_info:
        guest_name: "{{ custom_vm_name | default(vm_name) }}"
      register: vm_tools
      until: vm_tools.guests[0].guest_tools_status | default(false) == "guestToolsRunning"
      retries: "{{ (powerstate_agent_info_timeout if powerstate_agent_info_timeout >= 5 else 5) // 5 }}"
      delay: 5
