---
- name: Restarting {{ custom_vm_name | default(vm_name) }}...
  vmware.vmware.vm_powerstate:
    name: "{{ custom_vm_name | default(vm_name) }}"
    datacenter: "{{ datacenter }}"
    state: "{{ 'reboot-guest' if powerstate_vcenter_vm_info.guests[0].hw_power_status == 'poweredOn' else 'powered-on' }}"
  delegate_to: localhost
  become: false
