- name: Delegating suspend tasks to localhost...
  delegate_to: localhost
  become: false
  block:
    - name: Suspending {{ custom_vm_name | default(vm_name) }}...
      vmware.vmware.vm_powerstate:
        name: "{{ custom_vm_name | default(vm_name) }}"
        datacenter: "{{ datacenter }}"
        state: suspended

    - name: Waiting until {{ custom_vm_name | default(vm_name) }} is suspended...
      vmware.vmware.guest_info:
        guest_name: "{{ custom_vm_name | default(vm_name) }}"
      register: vm_tools
      until: vm_tools.guests[0].hw_power_status == "suspended"
      retries: "{{ (powerstate_agent_info_timeout if powerstate_agent_info_timeout >= 5 else 5) // 5 }}"
      delay: 5
