---
# Universal
- name: Updating SSHD MaxAuthTries for Cloud {{ inventory_hostname }}...
  when: os_configuration_configure_ssh_maxauthtries
  block:
    - name: Setting SSHD MaxAuthTries to {{ os_configuration_ssh_maxauthtries }}...
      ansible.builtin.replace:
        dest: /etc/ssh/sshd_config
        regexp: .*MaxAuthTries.*
        replace: MaxAuthTries {{ os_configuration_ssh_maxauthtries }}
      register: maxauthtries

    - name: Restarting SSHD... # noqa: no-handler
      ansible.builtin.systemd:
        name: "{{ os_configuration_os_family_service_name[ansible_os_family] | default('sshd') }}"
        state: restarted
      when: maxauthtries.changed

# AWS
- name: Cleaning up {{ infra_env }} configurations for {{ inventory_hostname }}...
  when: infra_env in os_configuration_cloud_envs
  block:
    - name: Removing cloud managed hostname...
      ansible.builtin.replace:
        dest: /etc/cloud/cloud.cfg
        regexp: ^ - update_etc_hosts
        replace: "# - update_etc_hosts"

- name: Installing Gnome for Ubuntu Desktop...
  ansible.builtin.apt:
    name: ubuntu-gnome-desktop
    state: present
    update_cache: true
  when: group_names | intersect(["os_ubuntu_desktop_20_04", "os_ubuntu_desktop_22_04", "os_ubuntu_desktop_24_04"]) | length > 0

- name: Installing Xfce for Kali...
  ansible.builtin.apt:
    name: kali-desktop-xfce
    state: present
    update_cache: true
  when: ansible_distribution == "Kali"

- name: Including XRDP roles...
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - nova.core.linux_xrdp_server
    - nova.core.linux_xrdp_keyboard
  when: group_names | intersect(["os_ubuntu_desktop_20_04", "os_ubuntu_desktop_22_04", "os_ubuntu_desktop_24_04", "os_kali"]) | length > 0
