---
# After the initial configuration is done its not needed and will slow down boot in most cases
- name: Purging cloud-init...
  ansible.builtin.package:
    name: cloud-init
    state: absent
    purge: true

# The way Linode VM disks are configured requires fixing the grub-pc install device
# Otherwise the update will fail without manual interactions
- name: Fixing Linode grub-pc configuration...
  when: infra_env == "linode"
  block:
    - name: Checking if grub-pc is installed...
      ansible.builtin.command: dpkg-query -W -f='${Status}' grub-pc
      register: grub_pc
      changed_when: false
      failed_when: false

    - name: Fixing grub-pc install device...
      when: "'install ok' in grub_pc.stdout"
      block:
        - name: Finding boot disk...
          ansible.builtin.command: findmnt -n -o SOURCE /
          register: boot_disk
          changed_when: false

        - name: Pre-seeding grub-pc install device...
          ansible.builtin.debconf:
            name: grub-pc
            question: grub-pc/install_devices
            vtype: multiselect
            value: "{{ boot_disk.stdout | trim }}"

        - name: Pre-seeding grub-pc install_devices_empty...
          ansible.builtin.debconf:
            name: grub-pc
            question: grub-pc/install_devices_empty
            vtype: boolean
            value: false

- name: Installing Gnome for Ubuntu Desktop...
  when: group_names | select('match', '^os_ubuntu_desktop') | list | length > 0
  block:
    - name: Trying to install Gnome...
      block:
        # The Gnome installation can fail if the OS is not fully up-to-date
        - name: Including nova.core.updates role...
          ansible.builtin.include_role:
            name: nova.core.updates

        - name: Installing Gnome...
          ansible.builtin.apt:
            name: ubuntu-gnome-desktop
            state: present
            update_cache: true

      rescue:
        - name: Restarting {{ custom_vm_name | default(vm_name) }} VM...
          ansible.builtin.include_role:
            name: nova.core.powerstate
          vars:
            restart: true

        - name: Including nova.core.updates role...
          ansible.builtin.include_role:
            name: nova.core.updates

        - name: Retrying Gnome installation...
          ansible.builtin.apt:
            name: ubuntu-gnome-desktop
            state: present
            update_cache: true

- name: Installing Xfce for Kali...
  when: ansible_facts.distribution == "Kali"
  block:
    - name: Trying to install Xfce...
      block:
        # The Xfce installation can fail if the OS is not fully up-to-date
        - name: Including nova.core.updates role...
          ansible.builtin.include_role:
            name: nova.core.updates

        - name: Installing Xfce...
          ansible.builtin.apt:
            name: kali-desktop-xfce
            state: present
            update_cache: true

      rescue:
        - name: Restarting {{ custom_vm_name | default(vm_name) }} VM...
          ansible.builtin.include_role:
            name: nova.core.powerstate
          vars:
            restart: true

        - name: Including nova.core.updates role...
          ansible.builtin.include_role:
            name: nova.core.updates

        - name: Retrying Xfce installation...
          ansible.builtin.apt:
            name: kali-desktop-xfce
            state: present
            update_cache: true

- name: Including XRDP roles...
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - nova.core.linux_xrdp_server
    - nova.core.linux_xrdp_keyboard
  when: group_names | select('match', '^os_ubuntu_desktop') | list | length > 0
    or ansible_facts.distribution | default('') == "Kali"
