---
start_vm_after_snapshot: true
start_vm_after_revert: true
remove_all_snapshots: false
live_snap: false # Creates a snapshot while the VM is running

# Agent can be VMTools, Qemu-guest-agent, etc.
snapshots_agent_info_timeout: 180
