---
- name: Waiting for network configuration command to finish for {{ inventory_hostname }}...
  ansible.builtin.uri:
    url: https://{{ vmware_defaults.hostname }}/api/vcenter/vm/{{ configure_networking_vsphere_vm_id
      }}/guest/processes/{{ network_config_command.json }}?action=get
    method: POST
    headers:
      vmware-api-session-id: "{{ vcenter_session_api_key.json }}"
    body:
      credentials: "{{ rest_api_credentials }}"
    status_code: 200
    body_format: json
    validate_certs: "{{ validate_vmware_certs }}"
  register: network_config_command_status
  until: network_config_command_status.json.exit_code is defined
  retries: "{{ (configure_networking_command_wait_timeout if configure_networking_command_wait_timeout >= 3 else 3) // 3 }}"
  delay: 3

- name: ERROR
  ansible.builtin.fail:
    msg: |
      The following command did not complete successfully on {{ inventory_hostname }}:
      {{ network_config_command_status.json.command }}
  when: network_config_command_status.json.exit_code != 0
