---
- name: Configuring network for supported connection modes...
  become: false
  delegate_to: localhost
  block:
    - name: Waiting for VMware tools to become available...
      community.vmware.vmware_guest_tools_wait:
        name: "{{ custom_vm_name | default(vm_name) }}"
      register: vcenter_vm_info

    - name: Setting VM ID fact and creating a list of MAC addresses...
      ansible.builtin.set_fact:
        configure_networking_vsphere_vm_id: "{{ vcenter_vm_info.instance.moid }}"
        configure_networking_mac_addresses: "{{ vcenter_vm_info.instance | dict2items
          | selectattr('key', 'match', '^hw_eth[0-9]+$') | map(attribute='value.macaddress') | list }}"

    - name: Getting REST API token...
      ansible.builtin.uri:
        url: https://{{ vmware_defaults.hostname }}/api/session
        method: POST
        user: "{{ vmware_defaults.username }}"
        password: "{{ vmware_defaults.password }}"
        force_basic_auth: true
        status_code: 201
        body_format: json
        validate_certs: "{{ vmware_defaults.validate_certs }}"
      no_log: true
      register: vcenter_session_api_key

    # Since the vSphere API can be quite unstable especially under load, we implement a rescue loop here
    # to retry the network configuration up to 3 times before failing the task completely.
    - name: Including network configuration tasks...
      block:
        - name: Including {{ customization_method }} network configuration tasks...
          ansible.builtin.include_tasks: "{{ customization_method }}.yml"

      rescue:
        - name: NETWORK CONFIGURATION ERROR
          ansible.builtin.fail:
            msg: |
              Network configuration has failed {{ configure_networking_rescue_count | default(0) }} times.
              Check the errors above and {{ inventory_hostname }} host logs for more details.
          when: configure_networking_rescue_count | default(0) | int == 3

        - name: Setting rescue loop count...
          ansible.builtin.set_fact:
            configure_networking_rescue_count: "{{ configure_networking_rescue_count | default(0) | int + 1 }}"

        - name: Re-including vSphere network configuration tasks...
          ansible.builtin.include_tasks: main.yml
