---
- name: Including nova.core.customization_pre_vm_role role...
  ansible.builtin.include_role:
    name: nova.core.customization_pre_vm_role

- name: Including vSphere specific configuration tasks...
  ansible.builtin.include_tasks: vsphere.yml
  when: infra_env == "vsphere"

- name: Including updates role...
  ansible.builtin.include_role:
    name: nova.core.updates
  when: template_os_configuration_update_system

# To reboot the machine after updates if required and avoid future issues
- name: Flush handlers...
  ansible.builtin.meta: flush_handlers

- name: Configure Windows machine
  ansible.builtin.include_tasks: windows.yml
  when: ansible_system | default(false) == "Win32NT"

- name: Including Unix configuration tasks...
  ansible.builtin.include_tasks: unix.yml
  when:
    - ansible_system | default([]) in ["Linux", "FreeBSD"]
    - ansible_network_os is not defined # Since PFsens and OPNsense also return FreeBSD as ansible_system

- name: Configure RouterOS machine
  ansible.builtin.include_tasks: routeros.yml
  when: ansible_network_os | default(false) == "community.routeros.routeros"

- name: Configure OPNsense machine
  ansible.builtin.include_tasks: opnsense.yml
  when: ansible_network_os | default(false) == "opnsense"

- name: Configure Pfsense machine
  ansible.builtin.include_tasks: pfsense.yml
  when: ansible_network_os | default(false) == "pfsense"

- name: Configure VyOS machine
  ansible.builtin.include_tasks: vyos.yml
  when: ansible_network_os | default(false) == 'vyos.vyos.vyos'

- name: Including following role...
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - nova.core.customization # Customize should be after updates in case updates revert some configs
    - nova.core.customization_post_vm_role
    - nova.core.finalize
    - nova.core.cleanup

- name: Including sysprep role...
  ansible.builtin.include_role:
    name: nova.core.win_sysprep
  when:
    - template_os_configuration_sysprep
    - ansible_system | default(false) == "Win32NT"

- name: Including snapshots role...
  ansible.builtin.include_role:
    name: nova.core.snapshots
  vars:
    snapshot_mode: clean-snap
    snapshot_name: LinkedCloneSource
    start_vm_after_snapshot: false

- name: Ending play for templates...
  ansible.builtin.meta: end_host
