---
- name: Including vSphere specific configuration tasks...
  when: infra_env == "vsphere"
  block:
    # Needed for VMware Tools authentication to work
    - name: Allowing VMware Tools authentication...
      ansible.builtin.lineinfile:
        path: /usr/local/etc/pam.d/vmtoolsd
        regexp: ^auth.*
        line: auth       sufficient       pam_permit.so

# SSHD Configuration
# This to avoid errors when someone has more that 6 SSH keys in their agent
- name: Increasing SSHD MaxAuthTries to {{ template_os_configuration_increase_maxauthtries_value }}...
  ansible.builtin.lineinfile:
    path: /usr/local/etc/inc/plugins.inc.d/openssh.inc
    regexp: .*$sshconf .= "MaxAuthTries.*
    insertafter: .*UseDNS.*
    line: '    $sshconf .= "MaxAuthTries {{ template_os_configuration_increase_maxauthtries_value }}\n"; # To avoid errors with more than 6 SSH keys'
  when: template_os_configuration_increase_maxauthtries
