---
- name: Including sysprep fix tasks...
  when: ansible_distribution | regex_search('Microsoft Windows 1(0|1).*') != none # Windows 10 and 11
  block:
    - name: Removing sysprep-blocking packages from {{ ansible_distribution }}...
      ansible.windows.win_shell: |
        Get-AppxPackage Microsoft.BingSearch* | Remove-AppPackage
        Get-AppxPackage Microsoft.Copilot* | Remove-AppPackage
        Get-AppxPackage Microsoft.Edge.GameAssist* | Remove-AppPackage
        Get-AppxPackage Microsoft.OneDriveSync* | Remove-AppPackage
        Get-AppxPackage Microsoft.TimeTravelDebugging* | Remove-AppPackage
        Get-AppxPackage Microsoft.WidgetsPlatformRuntime* | Remove-AppPackage
        Get-AppxPackage Microsoft.WinDbg* | Remove-AppPackage
        Get-AppxPackage Microsoft.XboxSpeechToTextOverlay* | Remove-AppPackage
        Get-AppxPackage MicrosoftWindows.Client.WebExperience* | Remove-AppPackage

    - name: Rebooting...
      ansible.windows.win_reboot:

# https://docs.ansible.com/ansible/latest/os_guide/windows_performance.html#fix-high-cpu-on-boot-for-vms-cloud-instances
- name: Recompiling DLLs after .NET updates
  community.windows.win_dotnet_ngen:

- name: Including sysprep tasks...
  ansible.builtin.include_tasks: sysprep.yml
  when: not win_sysprep_use_cloudbase_init | bool

- name: Including cloudbase-init tasks...
  ansible.builtin.include_tasks: cloudbase_init.yml
  when: win_sysprep_use_cloudbase_init | bool

- name: Including vSphere environment tasks...
  ansible.builtin.include_tasks: vsphere.yml
  when: infra_env == 'vsphere'

- name: Including Proxmox environment tasks...
  ansible.builtin.include_tasks: proxmox.yml
  when: infra_env == 'proxmox'
