---
- name: Waiting for Sysprep to finish...
  block:
    - name: Waiting until {{ custom_vm_name | default(vm_name) }} is powered off...
      vmware.vmware.guest_info:
        guest_name: "{{ custom_vm_name | default(vm_name) }}"
      register: vm_tools
      until: vm_tools.guests[0].hw_power_status == "poweredOff"
      retries: 90
      delay: 10
      delegate_to: localhost
      become: false

  rescue:
    - name: SYSPREP WAIT TIMEOUT
      ansible.builtin.fail:
        msg: |
          Timeout waiting for Sysprep to shut down the VM.
          Check the C:\Windows\System32\Sysprep\Panther\setuperr.log file on the VM for more details.
