---
- name: Creating networks for Azure VMs...
  become: false
  delegate_to: localhost
  block:
    - name: Create following virtual networks...
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ item.cloud_id }}"
        address_prefixes_cidr: "{{ item.addresses | map(attribute='address') | map('ansible.utils.ipaddr', 'network/prefix') | list }}"
        purge_address_prefixes: true
        purge_dns_servers: true
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.cloud_id }}"

    - name: Creating following subnets...
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ item.cloud_id }}"
        address_prefixes_cidr: "{{ item.addresses | map(attribute='address') | map('ansible.utils.ipaddr', 'network/prefix') | list }}"
        virtual_network: "{{ item.cloud_id }}"
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.cloud_id }}"
