name: Creating a new release and generating changelog

on:
  push:
    branches:
      - main

jobs:
  version_changelog_relase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Getting current version and generating changelog
        run: |
          TARGET_FILE="nova/core/galaxy.yml"
          CURRENT_VERSION=$(cat nova/core/galaxy.yml | grep version: | cut -d " " -f 2)

          echo $CURRENT_VERSION
          echo "LATEST_TAG=$CURRENT_VERSION" >> $GITHUB_ENV

          # Creating temp changelog file
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^^)..HEAD > CHANGELOG.md

      - uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.LATEST_TAG }}"
          bodyFile: CHANGELOG.md
